version: '2.1'

services:
  #Mura Server
  mura_mssql_cfml:
    image: ortussolutions/commandbox:latest
    depends_on:
      - mura_mssql
    environment:
      PORT: 8080
      SSL_PORT: 8443
      CFENGINE: lucee@5
      CFCONFIG_ADMINPASSWORD: NOT_SECURE_CHANGE
      MURA_ADMIN_USERNAME: admin
      MURA_ADMIN_PASSWORD: admin
      MURA_ADMINEMAIL: example@localhost.com
      MURA_APPRELOADKEY: appreload
      MURA_DATASOURCE: muradb
      MURA_DATABASE: muradb
      MURA_DBTYPE: mssql
      MURA_DBUSERNAME: sa
      MURA_DBPASSWORD: NOT_SECURE_CHANGE
      MURA_DBHOST: mura_mssql
      MURA_DBPORT: 3306
      MURA_SITEIDINURLS: "false"
      MURA_INDEXFILEINURLS: "false"
      LUCEE_JAVA_OPTS: "-Xms512m -Xmx1024m"
    volumes:
        - ../../../:/app
    ports:
        - "8080:8080"

  #MSSQL
  mura_mssql:
    image: microsoft/mssql-server-linux
    environment:
       ACCEPT_EULA: Y
       SA_PASSWORD: NOT_SECURE_CHANGE
    volumes:
        - mura_mssql_data:/var/lib/mysql
    ports:
        - "56666:1433"

volumes:
    - mura_mssql_data:/var/opt/mssql
